export enum ImageActionTypes {
  IMAGE_LOADING = 'IMAGE_LOADING',
  FETCH_IMAGES_PAGINATED = 'FETCH_IMAGES_PAGINATED',
  DELETE_IMAGES_PAGINATED = 'DELETE_IMAGES_PAGINATED',
  CREATE_IMAGE = 'CREATE_IMAGE',
  EDIT_IMAGE = 'EDIT_IMAGE',
  DELETE_IMAGE = 'DELETE_IMAGE',
  IMAGE_ERROR = 'IMAGE_ERROR',
}
