export enum LikedImageActionTypes {
  LIKED_IMAGE_LOADING = 'LIKED_IMAGE_LOADING',
  FETCH_LIKED_IMAGES_PAGINATED = 'FETCH_LIKED_IMAGES_PAGINATED',
  DELETE_LIKED_IMAGES_PAGINATED = 'DELETE_LIKED_IMAGES_PAGINATED',
  CREATE_LIKED_IMAGE = 'CREATE_LIKED_IMAGE',
  DELETE_LIKED_IMAGE = 'DELETE_LIKED_IMAGE',
  LIKED_IMAGE_ERROR = 'LIKED_IMAGE_ERROR',
}
