export enum UserActionTypes {
  CHECK_USER = 'CHECK_USER',
  FETCH_USER = 'FETCH_USER',
  CREATE_USER = 'CREATE_USER',
  EDIT_USER = 'EDIT_USER',
  DELETE_USER = 'DELETE_USER',
  USER_LOADING = 'USER_LOADING',
  USER_ERROR = 'USER_ERROR',
}
